### ISSUE TITLE
Should ZAMQP requests implement IDisableCSRFProtection?

### ISSUE THREAD

**Issue by datakurre** [collective/collective.zamqp#13]
@saily What do you think, how zamqp should handle implicit CSRF-protection in Plone 5 and now backported + enforced on Plone 4?

Easiest solution would be to make the request class inherit IDisableCSRFProtection when plone.protect with such interface exists. Or change the consming view to apply that interface to the request.

**Comment by saily** [comment]
i would prefer the way of Inheriting from `IDisableCSRFProtection`.

**Comment by saily** [comment]
Would it be possible to just disabe for worker instances using `PLONE_CSRF_DISABLED` environment variable in worker zope config?

**Comment by datakurre** [comment]
Yes. It's the current workaround.

Daniel Widerin kirjoitti ma lokakuuta 26 19:41:10 2015 GMT+0200:

**Comment by datakurre** [comment]
After I finally tried to test this, I found out that this really was not an issue and no additional interface was needed. The auto CSRF protection only affects authenticated requests and on the level where that's checked, ZAMQP requests are always anonymous.

Yet, the master is now running a roundtrip test at Travis for this fo bothr Plone 4 and Plone 5.
